const { chromium } = require('C:\\Users\\hugod\\AppData\\Roaming\\npm\\node_modules\\playwright');
(async () => {
  const browser = await chromium.launch();
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const mp = await mobile.newPage();
  await mp.goto('https://thepeptideradar.com', { waitUntil: 'networkidle', timeout: 25000 });
  await mp.screenshot({ path: 'C:\\Users\\hugod\\peptideradar\\screenshots\\mobile-home-top.png' });
  await mp.evaluate(() => window.scrollTo(0, 900));
  await new Promise(r=>setTimeout(r,400));
  await mp.screenshot({ path: 'C:\\Users\\hugod\\peptideradar\\screenshots\\mobile-home-guides.png' });
  await mp.evaluate(() => window.scrollTo(0, 2500));
  await new Promise(r=>setTimeout(r,400));
  await mp.screenshot({ path: 'C:\\Users\\hugod\\peptideradar\\screenshots\\mobile-home-lower.png' });
  const desk = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  const dp = await desk.newPage();
  await dp.goto('https://thepeptideradar.com', { waitUntil: 'networkidle', timeout: 25000 });
  await dp.screenshot({ path: 'C:\\Users\\hugod\\peptideradar\\screenshots\\desktop-home-top.png' });
  await dp.evaluate(() => window.scrollTo(0, 900));
  await new Promise(r=>setTimeout(r,400));
  await dp.screenshot({ path: 'C:\\Users\\hugod\\peptideradar\\screenshots\\desktop-home-guides.png' });
  await dp.evaluate(() => window.scrollTo(0, 2300));
  await new Promise(r=>setTimeout(r,400));
  await dp.screenshot({ path: 'C:\\Users\\hugod\\peptideradar\\screenshots\\desktop-home-lower.png' });
  await browser.close();
  console.log('done');
})().catch(e=>{console.error(e.message);process.exit(1)});
